-- 1. Reset (Drop all tables cleanly)
drop table if exists area_attendance cascade;
drop table if exists baggage cascade;
drop table if exists incidents cascade;
drop table if exists audit_logs cascade;
drop table if exists announcements cascade;
drop table if exists profiles cascade;
drop table if exists areas cascade;
drop table if exists floors cascade;
drop table if exists branches cascade;

-- Legacy drops just in case
drop table if exists floor_attendance cascade;
drop table if exists floor_settings cascade;
drop table if exists slots cascade;

-- 2. Create Tables (Order Matters)

-- Branches (New Entity)
create table branches (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Floors (Hierarchy: Branch -> Floor)
create table floors (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references branches(id) on delete cascade,
  floor_number int not null,
  label text, -- Optional label, e.g., "Ground Floor"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(branch_id, floor_number)
);

-- Areas (Hierarchy: Floor -> Area)
create table areas (
  id uuid primary key default gen_random_uuid(),
  floor_id uuid not null references floors(id) on delete cascade,
  name text not null, -- e.g., "Children's Area", "Computer Area"
  type text not null, -- e.g., "Children's Area", "Computer Area", "General Library", "Reading Nook"
  capacity int not null default 50,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(floor_id, name)
);

-- Profiles (Now references floors/areas, so must come AFTER them)
create table profiles (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  username text unique,
  role text check (role in ('admin', 'staff', 'volunteer')) not null,
  title text default 'Library Staff', -- Specific title (e.g. Librarian, Assistant)
  status text check (status in ('active', 'inactive', 'pending')) default 'active',
  email text unique,
  password text not null, -- Stores the user password
  avatar_url text, -- URL to profile picture
  assigned_branch_id uuid references branches(id), -- For staff/volunteers specific to a branch
  assigned_floor_id uuid references floors(id), -- Specific floor assignment
  assigned_area_id uuid references areas(id),   -- Specific area assignment
  permissions jsonb default '{}'::jsonb,        -- JSON object for module permissions: { "dashboard": true, "baggage": false, ... }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Storage Bucket Setup (Try to create if not exists - dependent on permissions)
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- Drop existing policies if they exist
drop policy if exists "Avatar images are publicly accessible" on storage.objects;
drop policy if exists "Anyone can upload an avatar" on storage.objects;
drop policy if exists "Anyone can update their own avatar" on storage.objects;

-- Create storage policies
create policy "Avatar images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Anyone can upload an avatar"
  on storage.objects for insert
  with check ( bucket_id = 'avatars' );
  
create policy "Anyone can update their own avatar"
  on storage.objects for update
  using ( bucket_id = 'avatars' );

-- Area Attendance
create table area_attendance (
  id bigint generated by default as identity primary key,
  patron_name text not null,
  patron_id text not null,
  area_id uuid not null references areas(id) on delete cascade,
  entry_time timestamp with time zone default timezone('utc'::text, now()) not null,
  exit_time timestamp with time zone,
  status text check (status in ('active', 'exited')) default 'active'
);

-- Baggage (Renamed from Slots, linked to Area)
create table baggage (
  id text primary key, -- e.g., "A1-L1" (Area1-Locker1)
  area_id uuid not null references areas(id) on delete cascade,
  status text check (status in ('occupied', 'available', 'maintenance')) default 'available',
  patron_name text,
  patron_id text,
  check_in_time timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Audit Logs (Scoped by Branch)
create table audit_logs (
  id bigint generated by default as identity primary key,
  branch_id uuid references branches(id), -- Nullable if system-wide
  user_name text not null,
  action text not null,
  module text not null,
  details text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Incidents (Scoped by Branch/Area)
create table incidents (
  id bigint generated by default as identity primary key,
  branch_id uuid not null references branches(id) on delete cascade,
  area_id uuid references areas(id), -- Optional specific area
  patron_id text,
  patron_name text,
  type text not null,
  description text not null,
  status text check (status in ('open', 'resolved', 'investigating')) default 'open',
  reported_by text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone
);

-- Announcements (Scoped by Branch)
create table announcements (
  id bigint generated by default as identity primary key,
  branch_id uuid references branches(id) on delete cascade, -- Nullable if global announcement
  title text not null,
  message text not null,
  module text,
    created_by text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    scheduled_at timestamp with time zone default timezone('utc'::text, now()),
    target_audience text default 'all', -- 'all', 'staff', 'volunteer'
    target_user_id uuid references profiles(id), -- Specific user targeting
    is_active boolean default true
);

-- 3. Enable RLS
alter table branches enable row level security;
alter table profiles enable row level security;
alter table floors enable row level security;
alter table areas enable row level security;
alter table area_attendance enable row level security;
alter table baggage enable row level security;
alter table audit_logs enable row level security;
alter table incidents enable row level security;
alter table announcements enable row level security;

-- 4. Create Policies
-- For simplicity, allowing public access for now as per original. 
-- In production, these should be scoped to auth.uid() and branch checks.
create policy "Public Access" on branches for all using (true);
create policy "Public Access" on profiles for all using (true);
create policy "Public Access" on floors for all using (true);
create policy "Public Access" on areas for all using (true);
create policy "Public Access" on area_attendance for all using (true);
create policy "Public Access" on baggage for all using (true);
create policy "Public Access" on audit_logs for all using (true);
create policy "Public Access" on incidents for all using (true);
create policy "Public Access" on announcements for all using (true);

-- 5. Insert Seed Data

-- Insert Default Branches
insert into branches (name) values 
('ValACE Malinta'),
('ValACE Marulas'),
('ValACE Gen. T. De Leon'),
('ValACE Mapulang Lupa');

-- Insert Default Floors and Areas (Example for ValACE Malinta)
do $$
declare
  v_branch_id uuid;
  v_floor_id uuid;
  v_area_id uuid;
begin
  -- Get ID for Malinta
  select id into v_branch_id from branches where name = 'ValACE Malinta';

  -- Create 3 Floors for Malinta
  for f in 1..3 loop
    insert into floors (branch_id, floor_number, label)
    values (v_branch_id, f, 'Floor ' || f)
    returning id into v_floor_id;

    -- Create Areas for each floor
    -- Example: General Library on all floors, Children's Area on Floor 1
    insert into areas (floor_id, name, type, capacity)
    values (v_floor_id, 'General Area ' || f, 'General Library', 40)
    returning id into v_area_id;
    
    -- Create Baggage Lockers for this area
    for s in 1..10 loop
       insert into baggage (id, area_id, status)
       values ('M-F' || f || '-A-L' || s, v_area_id, 'available');
    end loop;

    if f = 1 then
       insert into areas (floor_id, name, type, capacity)
       values (v_floor_id, 'Childrens Area', 'Childrens Area', 20);
    end if;
  end loop;

  -- Repeat logic for other branches if needed, or keeping it distinct in loop
end $$;

-- 6. Insert Default Admin User
INSERT INTO profiles (
    full_name,
    email,
    password,
    role,
    status,
    title,
    permissions
) VALUES (
    'System Administrator',
    'admin@valtrack.com',
    'admin123',
    'admin',
    'active',
    'System Administrator',
    '{"all": true}'
);

-- Create baggage_logs table to track history
create table baggage_logs (
  id bigint generated by default as identity primary key,
  baggage_id text, -- ID of the locker/baggage slot
  area_id uuid references areas(id), -- To track which area
  branch_id uuid references branches(id), -- To track which branch (optional but good for filtering)
  patron_name text,
  patron_id text,
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table baggage_logs enable row level security;
create policy "Public Access" on baggage_logs for all using (true);

-- Trigger to log baggage checkout
create or replace function log_baggage_checkout() returns trigger as $$
begin
  -- If status changes from 'occupied' to 'available', record it
  if old.status = 'occupied' and new.status = 'available' then
    insert into baggage_logs (baggage_id, area_id, patron_name, patron_id, check_in_time, check_out_time)
    values (old.id, old.area_id, old.patron_name, old.patron_id, old.check_in_time, now());
  end if;
  return new;
end;
$$ language plpgsql;

create trigger trigger_log_baggage_checkout
after update on baggage
for each row
execute function log_baggage_checkout();
