/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/AllHeader/OverallHeader`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Area Capacity/FloorAreaCapacity`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/VerificationSubmitted`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/_layout1`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/QR/UserQRCode`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Settings/UserSettings`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/UserAnalytics/CheckInAnalytics`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/AllHeader/OverallHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Area Capacity/FloorAreaCapacity`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Home/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Home/Footer`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Home/Notification`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Library Visitor/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Library Visitor/Navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Library Visitor/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Library Visitor/VerificationSubmitted`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Library Visitor/_layout1`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/QR/UserQRCode`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/Settings/UserSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/Patron/UserAnalytics/CheckInAnalytics`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Patron/AllHeader/OverallHeader${`?${string}` | `#${string}` | ''}` | `/Patron/Area Capacity/FloorAreaCapacity${`?${string}` | `#${string}` | ''}` | `/Patron/Home/Dashboard${`?${string}` | `#${string}` | ''}` | `/Patron/Home/Footer${`?${string}` | `#${string}` | ''}` | `/Patron/Home/Notification${`?${string}` | `#${string}` | ''}` | `/Patron/Library Visitor/LoginPage${`?${string}` | `#${string}` | ''}` | `/Patron/Library Visitor/Navigation${`?${string}` | `#${string}` | ''}` | `/Patron/Library Visitor/SignUp${`?${string}` | `#${string}` | ''}` | `/Patron/Library Visitor/VerificationSubmitted${`?${string}` | `#${string}` | ''}` | `/Patron/Library Visitor/_layout1${`?${string}` | `#${string}` | ''}` | `/Patron/QR/UserQRCode${`?${string}` | `#${string}` | ''}` | `/Patron/Settings/UserSettings${`?${string}` | `#${string}` | ''}` | `/Patron/UserAnalytics/CheckInAnalytics${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/AllHeader/OverallHeader`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Area Capacity/FloorAreaCapacity`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Home/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/VerificationSubmitted`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Library Visitor/_layout1`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/QR/UserQRCode`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/Settings/UserSettings`; params?: Router.UnknownInputParams; } | { pathname: `/Patron/UserAnalytics/CheckInAnalytics`; params?: Router.UnknownInputParams; };
    }
  }
}
